### ISSUE TITLE
the meaning of the results

### ISSUE THREAD

**Issue by wjczf123** [Wangpeiyi9979/ESD#1]
Hi! I have a detailed question that the code prints
            Batch f1 [ SNIPS ]: [Beam Soft Nms]: ( p: {:.4f}; r: {:.4f}; f1: {:.4f} ) beam_size :{} k:{}, u:{}, delta:{}
            Batch f1 [ SNIPS ]: [Origin       ]: ( p: {:.4f}; r: {:.4f}; f1: {:.4f} )
            All   f1 [FewNERD]: [Beam Soft Nms]: ( p: {:.4f}; r: {:.4f}; f1: {:.4f} ) beam_size :{} k:{}, u:{}, delta:{}
            All   f1 [FewNERD]: [Origin       ]: ( p: {:.4f}; r: {:.4f}; f1: {:.4f} ).

What does this mean? I guess that:
If I use SNIPS dataset, I can get the results through the corresponding Batch F1. If I use FewNERD dataset, I can get the results through the corresponding All F1. Is my guess correct? Thanks.

**Comment by Wangpeiyi9979** [comment]
Yes, you are right.☺

**Comment by wjczf123** [comment]
OK. Thank you a lot.
