### ISSUE TITLE
关于__get_spans__函数中的query set的tag的获取

### ISSUE THREAD

**Issue by yiphingzhang** [Wangpeiyi9979/ESD#2]
①if self.is_support == False:
      tag = tag - self.opt.O_class_num + 1 # for query, O1, O2, O3 -> O, entity_tag -> entity_tag - 2
请问这里，为什么要减2啊？之前根据support set，得到了tag2label, label2tag。这两个字典，就是下标和槽名的一一对应，那query set里获取tag的时候，减2不会把这个对应关系搞混吗？
②上面那两句代码的下一行，gold_entitys.add((b, e - 1, tag))。请问这里为什么还要减1？在函数 get_entity里，        
if end_of_chunk(prev_tag, tag, prev_type, type_):
            chunks.append((prev_type, begin_offset, i-1))
此处加到chunks里的，不是已经i-1了吗？
期待您的解答，谢谢

**Comment by Wangpeiyi9979** [comment]
Hi，您好。
①：对于每个task，我们有support set和一个query。假设这个task有N个关系：
首先，我们通过support set中的span初步得到所有的prototypes，包括`O1，O2，O3，E1, ..., EN`。
然后，O1，O2，O3会再次通过attention操作得到一个O类，因此，最后的prototypes是`O，E1，..., EN`. 。
tag2label，label2tag对应`O1，O2，O3，E1, ..., EN`。我们预测每个query span的时候，是用这个query span和prototypes `O，E1，..., EN`做匹配，因此要存的query span的标签应该对应 `O，E1，..., EN`，
所以query中的entity span的标签，要在label2tag得到的标签的基础上减2，才能从对应`O1，O2，O3，E1, ..., EN`转换到对应s `O，E1，..., EN`。

②：我记得get_entity得到的span边界是前闭后开的。这里我是按照前闭后闭存到gold_entity里去的，所以要-1。
![image](https://user-images.githubusercontent.com/42565075/179341541-68c8e091-d475-43ee-9f84-da1f8f24a4ae.png)

**Comment by yiphingzhang** [comment]
明白了，非常感谢您的耐心解答！（PS：觉得您的代码风格挺好的哈哈，还在模块那里贴心地用注释给划分开，赞！

**Comment by Wangpeiyi9979** [comment]
谢谢肯定，很高兴能够帮助到您。😀
