### ISSUE TITLE
SoftNMS

### ISSUE THREAD

**Issue by wjczf123** [Wangpeiyi9979/ESD#4]
Hi, peiyi.
I have two detailed questions about paper and code:
1. Is SoftNMS equivalent to a greedy (i.e., we pick the span with the highest probability each time, and the tokens in this span will not be selected again) strategy under FewNERD and SNIPS dataset? There is no nested entity on these two datasets.
2. The input of bert needs mask:
support_out = self.word_encoder(support['word'], output_hidden_states=True, return_dict=True)  # [num_sent, number_of_tokens, 768]
query_out = self.word_encoder(query['word'], output_hidden_states=True, return_dict=True)  # [num_sent, number_of_tokens, 768]

 query_out = self.word_encoder(query['word'], query['word'] != 0,output_hidden_states=True, return_dict=True)

**Comment by Wangpeiyi9979** [comment]
1、Yes. SoftNMS is equivalent to a greedy strategy under FewNERD and SNIPS.
2、Thank you for the reminder. I forgot to pass in ```mask``` when I was writing the code.

**Comment by wjczf123** [comment]
OK. Thank you a lot. Hope you have a nice day.

**Comment by wjczf123** [comment]
Hi, @Wangpeiyi9979.
I print this output of FewNERD dataset.
It outputs some strange results.
For example, [(0, 3, 3), (5, 8, 3), (0, 8, 5)].

**Comment by Wangpeiyi9979** [comment]
Hi, are these the outputs of Beam SoftNMS?

**Comment by wjczf123** [comment]
Yeah. I run it using the default configuration.

**Comment by Wangpeiyi9979** [comment]
Hi, I checked the code in ```util/utils.py ```.  
With the default configuration, L199 should remove the overlapping spans.  In other words, (5, 8, 3) and (0, 8, 5) should not be the output of the same sentence.
I also reran the code in the FewNERD 5-way 1-2 shot and I did not find any overlapping spans.
Is [(0, 3, 3), (5, 8, 3), (0, 8, 5)] the result of multiple sentences?
Maybe there is something I got wrong.  If you find it, please let me know. 
Thanks.

**Comment by wjczf123** [comment]
Thank you. Does the result change?

**Comment by wjczf123** [comment]
[(0, 3, 3), (5, 8, 3), (0, 8, 5)] is the result in a sentence.

**Comment by Wangpeiyi9979** [comment]
It is strange, I run the example:
![image](https://user-images.githubusercontent.com/42565075/200798885-7317554b-42e0-4f00-878d-9d65fd806303.png)
and it returns ```[[(5, 8, 3), (0, 3, 3)]]```
the function ```beam_search_soft_nms``` removes the overlapping spans.

**Comment by wjczf123** [comment]
I print the output of 22-episode in the test set.
The output is [[], [(0, 3, 3), (5, 8, 3), (0, 8, 5)], [(3, 5, 4), (7, 8, 4)], [], [(0, 1, 5)]].

**Comment by Wangpeiyi9979** [comment]
Hi, what is the input of the function ```beam_search_soft_nms``` in the 22-episode.

**Comment by wjczf123** [comment]
I donot save the input and only print the predicts of test episode.

**Comment by wjczf123** [comment]
I run it again for feedback.

**Comment by wjczf123** [comment]
Oh. I am very sorry. 
I notice that I change the parameters. 
Thank you very much for your help.
